[package]
name = "hasty"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
num-traits = "0.2.17"

[build-dependencies]
bindgen = "0.69.1"
cmake = "0.1.50"

[[bench]]
name = "bench_gemm"
harness = false
