[package]
name = "hasty"
version = "0.1.4"
authors = ["Toby Davis"]
description = "A Rust interface to system BLAS libraries for fast linear algebra operations"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Pencilcaseman/hasty"
license = "MIT"
keywords = ["blas", "linear-algebra", "matrix", "vector"]

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
num-traits = "0.2.17"

[build-dependencies]
bindgen = "0.69.1"
cmake = "0.1.50"

[[bench]]
name = "bench_gemm"
harness = false
