[package]
name = "hasty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    ".",
    "hasty_blas",
]

[dependencies]
hasty_blas = { version = "0.1.0", path = "hasty_blas" }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
num-traits = "0.2.17"

[[bench]]
name = "bench_gemm"
harness = false
