#ifndef HASTY_IMPL_OPENCL_ERROR_TYPES_HPP
#define HASTY_IMPL_OPENCL_ERROR_TYPES_HPP
#ifdef HASTY_IMPL_HAS_OPENCL

enum OpenCLErrorCode {
    Success,
    DeviceNotFound,
    DeviceNotAvailable,
    CompilerNotAvailable,
    MemoryObjectAllocationFailure,
    OutOfResources,
    OutOfHostMemory,
    ProfilingInfoNotAvailable,
    MemoryCopyOverlap,
    ImageFormatMismatch,
    ImageFormatNotSupported,
    BuildProgramFailure,
    MapFailure,

    InvalidValue,
    InvalidDeviceType,
    InvalidPlatform,
    InvalidDevice,
    InvalidContext,
    InvalidQueueProperties,
    InvalidCommandQueue,
    InvalidHostPointer,
    InvalidMemoryObject,
    InvalidImageFormatDescriptor,
    InvalidImageSize,
    InvalidSampler,
    InvalidBinary,
    InvalidBuildOptions,
    InvalidProgram,
    InvalidProgramExecutable,
    InvalidKernelName,
    InvalidKernelDefinition,
    InvalidKernel,
    InvalidArgIndex,
    InvalidArgValue,
    InvalidArgSize,
    InvalidKernelArgs,
    InvalidWorkDimension,
    InvalidWorkGroupSize,
    InvalidWorkItemSize,
    InvalidGlobalOffset,
    InvalidEventWaitList,
    InvalidEvent,
    InvalidOperation,
    InvalidGLObject,
    InvalidBufferSize,
    InvalidMipLevel,
    InvalidGlobalWorkSize,
    UnknownError,

    RoutineNotImplemented,
    InvalidMatrixA,
    InvalidMatrixB,
    InvalidMatrixC,
    InvalidVectorX,
    InvalidVectorY,
    InvalidDimension,
    InvalidLDA,
    InvalidLDB,
    InvalidLDC,
    InvalidIncX,
    InvalidIncY,
    InvalidMatrixBufferSizeA,
    InvalidMatrixBufferSizeB,
    InvalidMatrixBufferSizeC,
    InvalidVectorBufferSizeX,
    InvalidVectorBufferSizeY,
    TemporaryGEMMBufferTooSmall,
    BatchCountMustBePositive,
    TryingToOverrideParametersForInvalidKernel,
    MissingOverrideParameters,
    DeviceOutOfMemory,
    HalfPrecisionNotSupported,
    DoublePrecisionNotSupported,
    UnitSizedVectorInvalid,
    UnitSizedVectorTooSmall,
    DeviceEntryNotFound,
};

#endif // HASTY_IMPL_HAS_OPENCL
#endif // HASTY_IMPL_OPENCL_ERROR_TYPES_HPP