use crate::hasty_impl;

#[derive(Debug)]
pub enum OpenCLErrorCode {
    Success,
    DeviceNotFound,
    DeviceNotAvailable,
    CompilerNotAvailable,
    AllocationFailure,
    OutOfResources,
    OutOfHostMemory,
    ProfilingInfoNotAvailable,
    MemoryCopyOverlap,
    ImageFormatMismatch,
    ImageFormatNotSupported,
    BuildProgramFailure(String),
    MapFailure,
    InvalidValue,
    InvalidDeviceType,
    InvalidPlatform,
    InvalidDevice,
    InvalidContext,
    InvalidQueueProperties,
    InvalidCommandQueue,
    InvalidHostPointer,
    InvalidMemoryObject,
    InvalidImageFormatDescriptor,
    InvalidImageSize,
    InvalidBinary,
    InvalidBuildOptions,
    InvalidProgram,
    InvalidProgramExecutable,
    InvalidKernelName,
    InvalidKernelDefinition,
    InvalidKernel,
    InvalidArgIndex,
    InvalidArgValue,
    InvalidArgSize,
    InvalidKernelArgs,
    InvalidWorkDimension,
    InvalidWorkGroupSize,
    InvalidWorkItemSize,
    InvalidGlobalOffset,
    InvalidEventWaitList,
    InvalidEvent,
    InvalidOperation,
    InvalidGLObject,
    InvalidBufferSize,
    InvalidMipLevel,
    InvalidGlobalWorkSize,

    UnknownError,

    RoutineNotImplemented,
    InvalidMatrix(char),
    InvalidVector(char),
    InvalidDimension,
    InvalidLD(char),
    InvalidInc(char),
    InvalidMatrixBufferSize(char),
    InvalidVectorBufferSize(char),
    TempGemmBufferTooSmall,
    BatchCountMustBePositive,
    TryingToOverrideParametersForInvalidKernel,
    MissingOverrideParameters,
    DeviceOutOfMemory,
    HalfPrecisionNotSupported,
    UnitSizedVectorInvalid,
    UnitSizedVectorTooSmall,
    DeviceEntryNotFound,
}

impl OpenCLErrorCode {
    pub unsafe fn from_ffi(code: hasty_impl::OpenCLErrorCode) -> OpenCLErrorCode {
        match code {
            hasty_impl::OpenCLErrorCode_Success => OpenCLErrorCode::Success,
            hasty_impl::OpenCLErrorCode_DeviceNotFound => OpenCLErrorCode::DeviceNotFound,
            hasty_impl::OpenCLErrorCode_DeviceNotAvailable => OpenCLErrorCode::DeviceNotAvailable,
            hasty_impl::OpenCLErrorCode_CompilerNotAvailable => OpenCLErrorCode::CompilerNotAvailable,
            hasty_impl::OpenCLErrorCode_MemoryObjectAllocationFailure => OpenCLErrorCode::AllocationFailure,
            hasty_impl::OpenCLErrorCode_OutOfResources => OpenCLErrorCode::OutOfResources,
            hasty_impl::OpenCLErrorCode_OutOfHostMemory => OpenCLErrorCode::OutOfHostMemory,
            hasty_impl::OpenCLErrorCode_ProfilingInfoNotAvailable => OpenCLErrorCode::ProfilingInfoNotAvailable,
            hasty_impl::OpenCLErrorCode_MemoryCopyOverlap => OpenCLErrorCode::MemoryCopyOverlap,
            hasty_impl::OpenCLErrorCode_ImageFormatMismatch => OpenCLErrorCode::ImageFormatMismatch,
            hasty_impl::OpenCLErrorCode_ImageFormatNotSupported => OpenCLErrorCode::ImageFormatNotSupported,
            hasty_impl::OpenCLErrorCode_BuildProgramFailure => OpenCLErrorCode::BuildProgramFailure(String::from("")),
            hasty_impl::OpenCLErrorCode_MapFailure => OpenCLErrorCode::MapFailure,
            hasty_impl::OpenCLErrorCode_InvalidValue => OpenCLErrorCode::InvalidValue,
            hasty_impl::OpenCLErrorCode_InvalidDeviceType => OpenCLErrorCode::InvalidDeviceType,
            hasty_impl::OpenCLErrorCode_InvalidPlatform => OpenCLErrorCode::InvalidPlatform,
            hasty_impl::OpenCLErrorCode_InvalidDevice => OpenCLErrorCode::InvalidDevice,
            hasty_impl::OpenCLErrorCode_InvalidContext => OpenCLErrorCode::InvalidContext,
            hasty_impl::OpenCLErrorCode_InvalidQueueProperties => OpenCLErrorCode::InvalidQueueProperties,
            hasty_impl::OpenCLErrorCode_InvalidCommandQueue => OpenCLErrorCode::InvalidCommandQueue,
            hasty_impl::OpenCLErrorCode_InvalidHostPointer => OpenCLErrorCode::InvalidHostPointer,
            hasty_impl::OpenCLErrorCode_InvalidMemoryObject => OpenCLErrorCode::InvalidMemoryObject,
            hasty_impl::OpenCLErrorCode_InvalidImageFormatDescriptor => OpenCLErrorCode::InvalidImageFormatDescriptor,
            hasty_impl::OpenCLErrorCode_InvalidImageSize => OpenCLErrorCode::InvalidImageSize,
            hasty_impl::OpenCLErrorCode_InvalidSampler => OpenCLErrorCode::InvalidValue,
            hasty_impl::OpenCLErrorCode_InvalidBinary => OpenCLErrorCode::InvalidBinary,
            hasty_impl::OpenCLErrorCode_InvalidBuildOptions => OpenCLErrorCode::InvalidBuildOptions,
            hasty_impl::OpenCLErrorCode_InvalidProgram => OpenCLErrorCode::InvalidProgram,
            hasty_impl::OpenCLErrorCode_InvalidProgramExecutable => OpenCLErrorCode::InvalidProgramExecutable,
            hasty_impl::OpenCLErrorCode_InvalidKernelName => OpenCLErrorCode::InvalidKernelName,
            hasty_impl::OpenCLErrorCode_InvalidKernelDefinition => OpenCLErrorCode::InvalidKernelDefinition,
            hasty_impl::OpenCLErrorCode_InvalidKernel => OpenCLErrorCode::InvalidKernel,
            hasty_impl::OpenCLErrorCode_InvalidArgIndex => OpenCLErrorCode::InvalidArgIndex,
            hasty_impl::OpenCLErrorCode_InvalidArgValue => OpenCLErrorCode::InvalidArgValue,
            hasty_impl::OpenCLErrorCode_InvalidArgSize => OpenCLErrorCode::InvalidArgSize,
            hasty_impl::OpenCLErrorCode_InvalidKernelArgs => OpenCLErrorCode::InvalidKernelArgs,
            hasty_impl::OpenCLErrorCode_InvalidWorkDimension => OpenCLErrorCode::InvalidWorkDimension,
            hasty_impl::OpenCLErrorCode_InvalidWorkGroupSize => OpenCLErrorCode::InvalidWorkGroupSize,
            hasty_impl::OpenCLErrorCode_InvalidWorkItemSize => OpenCLErrorCode::InvalidWorkItemSize,
            hasty_impl::OpenCLErrorCode_InvalidGlobalOffset => OpenCLErrorCode::InvalidGlobalOffset,
            hasty_impl::OpenCLErrorCode_InvalidEventWaitList => OpenCLErrorCode::InvalidEventWaitList,
            hasty_impl::OpenCLErrorCode_InvalidEvent => OpenCLErrorCode::InvalidEvent,
            hasty_impl::OpenCLErrorCode_InvalidOperation => OpenCLErrorCode::InvalidOperation,
            hasty_impl::OpenCLErrorCode_InvalidGLObject => OpenCLErrorCode::InvalidGLObject,
            hasty_impl::OpenCLErrorCode_InvalidBufferSize => OpenCLErrorCode::InvalidBufferSize,
            hasty_impl::OpenCLErrorCode_InvalidMipLevel => OpenCLErrorCode::InvalidMipLevel,
            hasty_impl::OpenCLErrorCode_InvalidGlobalWorkSize => OpenCLErrorCode::InvalidGlobalWorkSize,

            hasty_impl::OpenCLErrorCode_UnknownError => OpenCLErrorCode::UnknownError,

            hasty_impl::OpenCLErrorCode_RoutineNotImplemented => OpenCLErrorCode::RoutineNotImplemented,
            hasty_impl::OpenCLErrorCode_InvalidMatrixA => OpenCLErrorCode::InvalidMatrix('A'),
            hasty_impl::OpenCLErrorCode_InvalidMatrixB => OpenCLErrorCode::InvalidMatrix('B'),
            hasty_impl::OpenCLErrorCode_InvalidMatrixC => OpenCLErrorCode::InvalidMatrix('C'),
            hasty_impl::OpenCLErrorCode_InvalidVectorX => OpenCLErrorCode::InvalidVector('X'),
            hasty_impl::OpenCLErrorCode_InvalidVectorY => OpenCLErrorCode::InvalidVector('Y'),
            hasty_impl::OpenCLErrorCode_InvalidDimension => OpenCLErrorCode::InvalidDimension,
            hasty_impl::OpenCLErrorCode_InvalidLDA => OpenCLErrorCode::InvalidLD('A'),
            hasty_impl::OpenCLErrorCode_InvalidLDB => OpenCLErrorCode::InvalidLD('B'),
            hasty_impl::OpenCLErrorCode_InvalidLDC => OpenCLErrorCode::InvalidLD('C'),
            hasty_impl::OpenCLErrorCode_InvalidIncX => OpenCLErrorCode::InvalidInc('X'),
            hasty_impl::OpenCLErrorCode_InvalidIncY => OpenCLErrorCode::InvalidInc('Y'),
            hasty_impl::OpenCLErrorCode_InvalidMatrixBufferSizeA => OpenCLErrorCode::InvalidMatrixBufferSize('A'),
            hasty_impl::OpenCLErrorCode_InvalidMatrixBufferSizeB => OpenCLErrorCode::InvalidMatrixBufferSize('B'),
            hasty_impl::OpenCLErrorCode_InvalidMatrixBufferSizeC => OpenCLErrorCode::InvalidMatrixBufferSize('C'),
            hasty_impl::OpenCLErrorCode_InvalidVectorBufferSizeX => OpenCLErrorCode::InvalidVectorBufferSize('X'),
            hasty_impl::OpenCLErrorCode_InvalidVectorBufferSizeY => OpenCLErrorCode::InvalidVectorBufferSize('Y'),
            hasty_impl::OpenCLErrorCode_TemporaryGEMMBufferTooSmall => OpenCLErrorCode::TempGemmBufferTooSmall,
            hasty_impl::OpenCLErrorCode_BatchCountMustBePositive => OpenCLErrorCode::BatchCountMustBePositive,
            hasty_impl::OpenCLErrorCode_TryingToOverrideParametersForInvalidKernel => OpenCLErrorCode::TryingToOverrideParametersForInvalidKernel,
            hasty_impl::OpenCLErrorCode_MissingOverrideParameters => OpenCLErrorCode::MissingOverrideParameters,
            hasty_impl::OpenCLErrorCode_DeviceOutOfMemory => OpenCLErrorCode::DeviceOutOfMemory,
            hasty_impl::OpenCLErrorCode_HalfPrecisionNotSupported => OpenCLErrorCode::HalfPrecisionNotSupported,
            hasty_impl::OpenCLErrorCode_UnitSizedVectorInvalid => OpenCLErrorCode::UnitSizedVectorInvalid,
            hasty_impl::OpenCLErrorCode_UnitSizedVectorTooSmall => OpenCLErrorCode::UnitSizedVectorTooSmall,
            hasty_impl::OpenCLErrorCode_DeviceEntryNotFound => OpenCLErrorCode::DeviceEntryNotFound,
            _ => OpenCLErrorCode::UnknownError
        }
    }
}

/// Configure OpenCL -- Temporary function. This will be replaced soon
pub fn configure_opencl() {
    unsafe {
        hasty_impl::configureOpenCL();
    }
}