name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hasty
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Update Rust
        run: |
          rustup update
          rustup component add rustfmt
          rustup component add clippy

      - name: Install OpenBLAS
        run: |
          sudo apt-get install libopenblas-dev

      - name: Compile and Test (No Features) (Debug)
        run: |
          cargo build --no-default-features
          cargo test --no-default-features

      - name: Compile and Test (BLAS) (Debug)
        run: |
          cargo build --features "blas"
          cargo test --features "blas"

      - name: Compile and Test (No Features) (Release)
        run: |
          cargo build --no-default-features --release
          cargo test --no-default-features --release

      - name: Compile and Test (BLAS) (Release)
        run: |
          cargo build --features "blas" --release
          cargo test --features "blas" --release

      - name: Benchmark
        run: |
          cargo bench --features "blas"

      - name: Store Benchmark Results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: target/criterion

      - name: Publish Release
        run: |
          cargo login ${{ secrets.CRATES_IO_LOGIN }}
          cargo publish
